'use strict';

import { readfile, stat } from 'fs';
import { connect } from 'ubus';
import { cursor } from 'uci';

let ubus = connect(null);

const UCI_CONFIG = 'frpc-advanced';
const CONFIG_FILE = '/var/etc/frpc-advanced/frpc.main.toml';
const MAX_CONFIG_SIZE = 524288;


function read_main_option(option, fallback) {
	try {
		let c = cursor();
		let value = c.get(UCI_CONFIG, 'main', option);
		return value == null ? fallback : value;
	}
	catch (e) {
		return fallback;
	}
}

function get_service_status() {
	let result = {
		ok: true,
		running: false,
		pid: null,
		instances: []
	};

	try {
		let response = ubus.call('service', 'list', { name: UCI_CONFIG });
		let instances = response && response[UCI_CONFIG] && response[UCI_CONFIG].instances;
		if (!instances)
			return result;

		for (let name in instances) {
			let instance = instances[name] || {};
			let item = {
				name: name,
				running: instance.running === true,
				pid: instance.pid || null
			};
			push(result.instances, item);
			if (item.running) {
				result.running = true;
				if (!result.pid)
					result.pid = item.pid;
			}
		}
	}
	catch (e) {
		result.ok = false;
		result.code = 'SERVICE_QUERY_FAILED';
	}

	return result;
}

function normalize_config_for_compare(content) {
	if (type(content) != 'string')
		return '';

	let sourceLines = split(content, "\n");
	let normalizedLines = [];

	for (let i = 0; i < length(sourceLines); i++) {
		let line = sourceLines[i];

		if (length(line) > 0 &&
		    substr(line, length(line) - 1, 1) == "\r")
			line = substr(line, 0, length(line) - 1);

		if (i == 0 &&
		    match(line, /^# Generated by luci-app-frpc-advanced/))
			continue;

		push(normalizedLines, line);
	}

	while (length(normalizedLines) > 0 &&
	       normalizedLines[length(normalizedLines) - 1] == "")
		normalizedLines = slice(normalizedLines, 0, length(normalizedLines) - 1);

	return join("\n", normalizedLines) + "\n";
}
const MAX_BACKUP_SIZE = 262144;

const internalMainKeys = {
	enabled: true,
	respawn: true,
	client_file: true,
	schema_version: true,
	run_user: true,
	server: true
};

/* Accepted on import for backward compatibility, but no longer restored/exported.
 * ImmortalWrt FRP 0.66.0 sends console stdout/stderr to procd/logd instead. */
const deprecatedLoggingKeys = {
	enable_logging: true,
	log__to: true,
	log__maxDays: true,
	std_redirect: true,
	log__disablePrintColor: true
};

const allowedSettingsKeys = {
	clientID: true,
	user: true,
	loginFailExit: true,
	enable_logging: true,
	log__level: true,
	log__to: true,
	log__maxDays: true,
	std_redirect: true,
	log__disablePrintColor: true,
	transport__protocol: true,
	transport__wireProtocol: true,
	transport__poolCount: true,
	transport__dialServerTimeout: true,
	transport__dialServerKeepalive: true,
	transport__connectServerLocalIP: true,
	transport__proxyURL: true,
	transport__quic__keepalivePeriod: true,
	transport__quic__maxIdleTimeout: true,
	transport__quic__maxIncomingStreams: true,
	transport__heartbeatInterval: true,
	transport__heartbeatTimeout: true,
	dnsServer: true,
	natHoleStunServer: true,
	udpPacketSize: true,
	includes: true,
	com_extra_options: true,
	webServer__addr: true,
	webServer__port: true,
	webServer__user: true,
	webServer__password: true,
	webServer__assetsDir: true,
	webServer__tls__certFile: true,
	webServer__tls__keyFile: true,
	webServer__pprofEnable: true,
	store__path: true
};

const allowedServerKeys = {
	enabled: true,
	alias: true,
	serverAddr: true,
	serverPort: true,
	auth__method: true,
	auth__token: true,
	auth__tokenSource__file__path: true,
	auth__tokenSource__type: true,
	auth__additionalScopes: true,
	auth__oidc__clientID: true,
	auth__oidc__clientSecret: true,
	auth__oidc__audience: true,
	auth__oidc__tokenEndpointURL: true,
	auth__oidc__scope: true,
	auth__oidc__trustedCaFile: true,
	auth__oidc__proxyURL: true,
	auth__oidc__insecureSkipVerify: true,
	transport__tls__enable: true,
	transport__tls__disableCustomTLSFirstByte: true,
	transport__tls__certFile: true,
	transport__tls__keyFile: true,
	transport__tls__trustedCaFile: true,
	transport__tls__serverName: true,
	transport__tcpMux: true,
	transport__tcpMuxKeepaliveInterval: true
};

const allowedRuleKeys = {
	enabled: true,
	name: true,
	type: true,
	visitor: true,
	localIP: true,
	localPort: true,
	remotePort: true,
	customDomains: true,
	subdomain: true,
	serverName: true,
	serverUser: true,
	bindAddr: true,
	bindPort: true,
	secretKey: true,
	allowUsers: true,
	protocol: true,
	maxRetriesAnHour: true,
	minRetryInterval: true,
	fallbackTo: true,
	fallbackTimeoutMs: true,
	keepTunnelOpen: true,
	natTraversal__disableAssistedAddrs: true,
	locations: true,
	hostHeaderRewrite: true,
	httpUser: true,
	httpPassword: true,
	routeByHTTPUser: true,
	transport__bandwidthLimit: true,
	transport__bandwidthLimitMode: true,
	transport__useEncryption: true,
	transport__useCompression: true,
	transport__proxyProtocolVersion: true,
	loadBalancer__group: true,
	loadBalancer__groupKey: true,
	healthCheck__type: true,
	healthCheck__path: true,
	healthCheck__timeoutSeconds: true,
	healthCheck__maxFailed: true,
	healthCheck__intervalSeconds: true,
	PlUgIn_type: true,
	unixPath: true,
	username: true,
	password: true,
	localPath: true,
	stripPrefix: true,
	PlUgIn_httpUser: true,
	PlUgIn_httpPassword: true,
	localAddr: true,
	crtPath: true,
	keyPath: true,
	PlUgIn_hostHeaderRewrite: true,
	enableHTTP2: true,
	extra_options: true,
	extra_options_plugin: true
};

function read_service_state() {
	let response = null;

	try {
		response = ubus.call('service', 'list', { name: UCI_CONFIG });
	}
	catch (e) {
		return 'unknown';
	}

	if (!response || type(response) != 'object')
		return 'unknown';

	let service = response[UCI_CONFIG];
	if (!service)
		return 'stopped';
	if (type(service) != 'object')
		return 'unknown';

	let instances = service.instances;
	if (!instances)
		return 'stopped';
	if (type(instances) != 'object')
		return 'unknown';

	for (let instanceName in instances) {
		if (instances[instanceName] && instances[instanceName].running === true)
			return 'running';
	}

	return 'stopped';
}

function is_forbidden_key(key) {
	return key == '__proto__' || key == 'constructor' || key == 'prototype';
}

function validate_option_value(scope, key, value) {
	if (type(value) == 'array') {
		for (let item in value) {
			if (type(item) != 'string')
				return { ok: false, code: 'VALIDATION_FAILED', stage: 'validate-array', message: scope + '.' + key + ' must contain strings only' };
			if (length(item) > 4096)
				return { ok: false, code: 'VALIDATION_FAILED', stage: 'validate-array', message: scope + '.' + key + ' contains an oversized value' };
		}
	}
	else if (type(value) == 'string') {
		if (length(value) > 4096)
			return { ok: false, code: 'VALIDATION_FAILED', stage: 'validate-value', message: scope + '.' + key + ' value exceeds 4096 bytes' };
	}
	else {
		return { ok: false, code: 'VALIDATION_FAILED', stage: 'validate-value', message: scope + '.' + key + ' must be a string or string array' };
	}

	return { ok: true };
}

function validate_option_object(scope, object, allowed) {
	if (!object || type(object) != 'object')
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-values', message: scope + ' must be an object' };

	let count = 0;
	for (let key in object) {
		if (is_forbidden_key(key) || substr(key, 0, 1) == '.')
			return { ok: false, code: 'INVALID_VALUES', stage: 'validate-option', message: 'forbidden option name: ' + scope + '.' + key };
		if (!allowed[key])
			return { ok: false, code: 'UNKNOWN_OPTION', stage: 'validate-option', message: 'unknown option: ' + scope + '.' + key };
		let checked = validate_option_value(scope, key, object[key]);
		if (!checked.ok)
			return checked;
		count++;
	}

	return { ok: true, option_count: count };
}

function validate_backup_object(backup) {
	if (!backup || type(backup) != 'object')
		return { ok: false, code: 'INVALID_FORMAT', stage: 'validate-schema', message: 'backup must be an object' };

	for (let key in backup) {
		if (is_forbidden_key(key))
			return { ok: false, code: 'INVALID_FORMAT', stage: 'validate-schema', message: 'forbidden backup field: ' + key };
		if (key != 'format' && key != 'schemaVersion' && key != 'settings' && key != 'servers' && key != 'rules')
			return { ok: false, code: 'INVALID_FORMAT', stage: 'validate-schema', message: 'unsupported backup field: ' + key };
	}

	if (backup.format != 'frpc-advanced-backup')
		return { ok: false, code: 'INVALID_FORMAT', stage: 'validate-format', message: 'unsupported backup format: ' + (backup.format || 'none') };
	if (backup.schemaVersion != 1)
		return { ok: false, code: 'INVALID_FORMAT', stage: 'validate-format', message: 'unsupported schema version: ' + (backup.schemaVersion || 'none') };
	if (!backup.settings || type(backup.settings) != 'object')
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-settings', message: 'settings must be an object' };
	if (type(backup.servers) != 'array')
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-servers', message: 'servers must be an array' };
	if (type(backup.rules) != 'array')
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-rules', message: 'rules must be an array' };

	let optionCount = 0;
	let settingsValidation = validate_option_object('settings', backup.settings, allowedSettingsKeys);
	if (!settingsValidation.ok)
		return settingsValidation;
	optionCount += settingsValidation.option_count;

	let selectedCount = 0;
	for (let i = 0; i < length(backup.servers); i++) {
		let server = backup.servers[i];
		if (!server || type(server) != 'object')
			return { ok: false, code: 'INVALID_VALUES', stage: 'validate-server', message: 'servers[' + i + '] must be an object' };
		if (!('selected' in server) || (server.selected !== true && server.selected !== false))
			return { ok: false, code: 'INVALID_VALUES', stage: 'validate-server', message: 'servers[' + i + '].selected must be boolean' };
		if (server.selected === true)
			selectedCount++;

		let clean = {};
		for (let key in server) {
			if (key == 'selected')
				continue;
			clean[key] = server[key];
		}
		let serverValidation = validate_option_object('servers[' + i + ']', clean, allowedServerKeys);
		if (!serverValidation.ok)
			return serverValidation;
		optionCount += serverValidation.option_count;
	}

	if (length(backup.servers) > 0 && selectedCount != 1)
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-selection', message: 'exactly one server must be selected' };
	if (length(backup.servers) == 0 && selectedCount != 0)
		return { ok: false, code: 'INVALID_VALUES', stage: 'validate-selection', message: 'no server may be selected when servers is empty' };

	for (let i = 0; i < length(backup.rules); i++) {
		let rule = backup.rules[i];
		if (!rule || type(rule) != 'object')
			return { ok: false, code: 'INVALID_VALUES', stage: 'validate-rule', message: 'rules[' + i + '] must be an object' };
		let ruleValidation = validate_option_object('rules[' + i + ']', rule, allowedRuleKeys);
		if (!ruleValidation.ok)
			return ruleValidation;
		optionCount += ruleValidation.option_count;
	}

	return {
		ok: true,
		section_count: 1 + length(backup.servers) + length(backup.rules),
		option_count: optionCount,
		server_count: length(backup.servers)
	};
}

function copy_user_options(section, skip) {
	let output = {};
	if (!section || type(section) != 'object')
		return output;

	for (let key in section) {
		if (substr(key, 0, 1) == '.')
			continue;
		if (skip && skip[key])
			continue;
		if (deprecatedLoggingKeys[key])
			continue;
		output[key] = section[key];
	}

	return output;
}

function backup_from_uci(current) {
	if (!current || type(current) != 'object' || !current.main || type(current.main) != 'object')
		return { ok: false, code: 'UCI_READ_FAILED', stage: 'normalize-current', message: 'unable to read current configuration' };

	let backup = {
		format: 'frpc-advanced-backup',
		schemaVersion: 1,
		settings: copy_user_options(current.main, internalMainKeys),
		servers: [],
		rules: []
	};
	let selectedId = current.main.server || '';
	let selectedCount = 0;

	for (let sectionName in current) {
		if (substr(sectionName, 0, 1) == '.' || sectionName == 'main')
			continue;
		let section = current[sectionName];
		if (!section || type(section) != 'object')
			continue;

		if (section['.type'] == 'server') {
			let server = copy_user_options(section, null);
			server.selected = sectionName == selectedId;
			if (server.selected)
				selectedCount++;
			push(backup.servers, server);
		}
		else if (section['.type'] == 'rule') {
			push(backup.rules, copy_user_options(section, null));
		}
	}

	if (length(backup.servers) > 0 && selectedCount != 1)
		return { ok: false, code: 'MAIN_SERVER_STALE', stage: 'normalize-current', message: 'current server selection is missing or stale' };

	return { ok: true, backup: backup };
}

function pseudo_sections(backup) {
	let sections = { main: { '.type': 'frpc' } };
	for (let key in backup.settings) {
		if (!deprecatedLoggingKeys[key])
			sections.main[key] = backup.settings[key];
	}

	for (let i = 0; i < length(backup.servers); i++) {
		let section = { '.type': 'server', selected: backup.servers[i].selected === true ? '1' : '0' };
		for (let key in backup.servers[i]) {
			if (key != 'selected')
				section[key] = backup.servers[i][key];
		}
		sections['server_' + (i + 1)] = section;
	}

	for (let i = 0; i < length(backup.rules); i++) {
		let section = { '.type': 'rule' };
		for (let key in backup.rules[i])
			section[key] = backup.rules[i][key];
		sections['rule_' + (i + 1)] = section;
	}

	return sections;
}

function value_equal(a, b) {
	if (type(a) != type(b))
		return false;
	if (type(a) == 'string')
		return a == b;
	if (type(a) == 'array') {
		if (length(a) != length(b))
			return false;
		for (let i = 0; i < length(a); i++) {
			if (type(a[i]) != 'string' || a[i] != b[i])
				return false;
		}
		return true;
	}
	return false;
}

function compare_sections(current, wanted) {
	let result = {
		added_sections: [],
		removed_sections: [],
		added_options: [],
		changed_options: [],
		removed_options: [],
		added_section_count: 0,
		removed_section_count: 0,
		added_option_count: 0,
		changed_option_count: 0,
		removed_option_count: 0,
		truncated: false
	};
	let MAX = 50;

	for (let sn in wanted) {
		if (substr(sn, 0, 1) == '.')
			continue;
		if (!current[sn]) {
			result.added_section_count++;
			if (length(result.added_sections) < MAX)
				push(result.added_sections, sn);
		}
	}

	for (let sn in current) {
		if (substr(sn, 0, 1) == '.')
			continue;
		if (!wanted[sn]) {
			result.removed_section_count++;
			if (length(result.removed_sections) < MAX)
				push(result.removed_sections, sn);
		}
	}

	for (let sn in wanted) {
		if (substr(sn, 0, 1) == '.')
			continue;
		let ws = wanted[sn];
		let cs = current[sn];

		if (!cs || type(cs) != 'object') {
			for (let key in ws) {
				if (substr(key, 0, 1) == '.')
					continue;
				result.added_option_count++;
				if (length(result.added_options) < MAX)
					push(result.added_options, sn + '.' + key);
			}
			continue;
		}

		if (ws['.type'] != cs['.type']) {
			result.added_section_count++;
			result.removed_section_count++;
			if (length(result.added_sections) < MAX)
				push(result.added_sections, sn);
			if (length(result.removed_sections) < MAX)
				push(result.removed_sections, sn);
			continue;
		}

		let seen = {};
		for (let key in ws) {
			if (substr(key, 0, 1) == '.')
				continue;
			seen[key] = true;
			if (!(key in cs)) {
				result.added_option_count++;
				if (length(result.added_options) < MAX)
					push(result.added_options, sn + '.' + key);
			}
			else if (!value_equal(ws[key], cs[key])) {
				result.changed_option_count++;
				if (length(result.changed_options) < MAX)
					push(result.changed_options, sn + '.' + key);
			}
		}

		for (let key in cs) {
			if (substr(key, 0, 1) == '.')
				continue;
			if (!seen[key]) {
				result.removed_option_count++;
				if (length(result.removed_options) < MAX)
					push(result.removed_options, sn + '.' + key);
			}
		}
	}

	if (result.added_section_count > MAX || result.removed_section_count > MAX ||
	    result.added_option_count > MAX || result.changed_option_count > MAX ||
	    result.removed_option_count > MAX)
		result.truncated = true;

	return result;
}

function parse_and_validate_backup(raw) {
	if (type(raw) != 'string' || length(raw) == 0)
		return { ok: false, code: 'INVALID_ARGUMENT', stage: 'read-argument', message: 'config must be a non-empty string' };
	if (length(raw) > MAX_BACKUP_SIZE)
		return { ok: false, code: 'FILE_TOO_LARGE', stage: 'read-argument', message: 'backup data exceeds 256KB' };

	let incoming = null;
	try {
		incoming = json(raw);
	}
	catch (e) {
		return { ok: false, code: 'INVALID_JSON', stage: 'parse-json', message: 'backup is not valid JSON' };
	}

	let validation = validate_backup_object(incoming);
	if (!validation.ok)
		return validation;

	return {
		ok: true,
		backup: incoming,
		section_count: validation.section_count,
		option_count: validation.option_count,
		server_count: validation.server_count
	};
}

function apply_backup(config, backup) {
	let c = cursor();
	let current = c.get_all(config);

	if (!current || type(current) != 'object' || !current.main || type(current.main) != 'object')
		return { ok: false, code: 'UCI_READ_FAILED', stage: 'read-current', message: 'unable to read current UCI configuration' };
	if (current.main['.type'] != 'frpc')
		return { ok: false, code: 'UCI_READ_FAILED', stage: 'read-current', message: 'main section type is not frpc' };

	for (let sectionName in current) {
		if (substr(sectionName, 0, 1) == '.' || sectionName == 'main')
			continue;
		if (c.delete(config, sectionName) !== true)
			return { ok: false, code: 'UCI_DELETE_FAILED', stage: 'delete-section', message: 'unable to delete section: ' + sectionName };
	}

	for (let key in current.main) {
		if (substr(key, 0, 1) == '.' || internalMainKeys[key])
			continue;
		if (c.delete(config, 'main', key) !== true)
			return { ok: false, code: 'UCI_DELETE_FAILED', stage: 'delete-option', message: 'unable to delete option: main.' + key };
	}

	if (current.main.server != null && c.delete(config, 'main', 'server') !== true)
		return { ok: false, code: 'UCI_DELETE_FAILED', stage: 'delete-option', message: 'unable to delete option: main.server' };

	for (let key in backup.settings) {
		if (deprecatedLoggingKeys[key])
			continue;
		if (c.set(config, 'main', key, backup.settings[key]) !== true)
			return { ok: false, code: 'UCI_SET_FAILED', stage: 'set-option', message: 'unable to set option: main.' + key };
	}

	let selectedServerIndex = null;
	for (let i = 0; i < length(backup.servers); i++) {
		let server = backup.servers[i];
		let sectionId = c.add(config, 'server');
		if (!sectionId)
			return { ok: false, code: 'UCI_CREATE_FAILED', stage: 'create-server', message: 'unable to create server section' };

		for (let key in server) {
			if (key == 'selected')
				continue;
			if (c.set(config, sectionId, key, server[key]) !== true)
				return { ok: false, code: 'UCI_SET_FAILED', stage: 'set-server', message: 'unable to set option: server.' + key };
		}
		if (server.selected === true)
			selectedServerIndex = i;
	}

	for (let i = 0; i < length(backup.rules); i++) {
		let rule = backup.rules[i];
		let sectionId = c.add(config, 'rule');
		if (!sectionId)
			return { ok: false, code: 'UCI_CREATE_FAILED', stage: 'create-rule', message: 'unable to create rule section' };

		for (let key in rule) {
			if (c.set(config, sectionId, key, rule[key]) !== true)
				return { ok: false, code: 'UCI_SET_FAILED', stage: 'set-rule', message: 'unable to set option: rule.' + key };
		}
	}

	if (c.commit(config) !== true)
		return { ok: false, code: 'UCI_COMMIT_FAILED', stage: 'commit', message: 'unable to commit UCI configuration' };

	if (selectedServerIndex != null) {
		let resolvedCursor = cursor();
		let selectedSection = resolvedCursor.get_all(config, '@server[' + selectedServerIndex + ']');
		if (!selectedSection || type(selectedSection) != 'object' ||
		    selectedSection['.type'] != 'server' ||
		    type(selectedSection['.name']) != 'string' || length(selectedSection['.name']) == 0)
			return { ok: false, code: 'UCI_SERVER_REFERENCE_FAILED', stage: 'verify-selected-server', message: 'unable to resolve restored selected server section' };

		if (resolvedCursor.set(config, 'main', 'server', selectedSection['.name']) !== true)
			return { ok: false, code: 'UCI_SET_FAILED', stage: 'select-server', message: 'unable to select restored server' };

		if (resolvedCursor.commit(config) !== true)
			return { ok: false, code: 'UCI_COMMIT_FAILED', stage: 'commit-selected-server', message: 'unable to commit selected server reference' };
	}

	let verifyCursor = cursor();
	if (selectedServerIndex != null) {
		let persistedServer = verifyCursor.get(config, 'main', 'server');
		if (type(persistedServer) != 'string' || length(persistedServer) == 0)
			return { ok: false, code: 'UCI_SERVER_REFERENCE_FAILED', stage: 'verify-selected-server', message: 'main.server is empty after restore' };

		let refSection = verifyCursor.get_all(config, persistedServer);
		if (!refSection || type(refSection) != 'object' || refSection['.type'] != 'server')
			return { ok: false, code: 'UCI_SERVER_REFERENCE_FAILED', stage: 'verify-selected-server', message: 'main.server does not reference an existing server section' };
	}

	return { ok: true };
}


return {
	'luci.frpc-advanced': {
		get_status: {
			call: function() {
				return get_service_status();
			}
		},

		get_version: {
			call: function(request) {
				let path = read_main_option('client_file', '/usr/bin/frpc');
				if (type(path) != 'string' ||
				    length(path) == 0 ||
				    length(path) > 1024 ||
				    !match(path, /^\/[A-Za-z0-9_.\/-]+$/)) {
					return { status: 'error', code: 'invalid_path' };
				}

				let fileStat = stat(path);
				if (!fileStat || (fileStat.mode & 73) == 0)
					return { status: 'error', code: 'not_executable' };

				return ubus.defer('file', 'exec', {
					command: path,
					params: [ '--version' ],
					env: {}
				}, function(code, response) {
					if (code != 0 || !response || type(response) != 'object' || response.code != 0) {
						request.reply({ status: 'error', code: 'exec_failed' });
						return;
					}

					let output = substr(response.stdout || '', 0, 128);
					let found = match(output, /v?[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.-]+)?/);
					if (!found || !found[0]) {
						request.reply({ status: 'error', code: 'unparseable' });
						return;
					}
					let version = found[0];
					if (match(version, /^v/)) version = substr(version, 1);
					request.reply({ status: 'ok', version: version });
				});
			}
		},

		get_config: {
			call: function() {
				try {
					let fileStat = stat(CONFIG_FILE);
					if (!fileStat)
						return { ok: true, exists: false, code: 'NOT_GENERATED', content: '', path: CONFIG_FILE };
					if (fileStat.size > MAX_CONFIG_SIZE)
						return { ok: false, exists: true, code: 'FILE_TOO_LARGE', content: '', path: CONFIG_FILE, size: fileStat.size };
					return {
						ok: true,
						exists: true,
						code: 'OK',
						content: readfile(CONFIG_FILE) || '',
						path: CONFIG_FILE,
						size: fileStat.size
					};
				}
				catch (e) {
					return { ok: true, exists: false, code: 'NOT_GENERATED', content: '', path: CONFIG_FILE };
				}
			}
		},

		get_config_compare: {
			call: function(request) {
				let service = get_service_status();
				let runtime = { exists: false, content: '', path: CONFIG_FILE, code: 'NOT_GENERATED', message: 'runtime configuration file not found' };
				let maxSize = 524288;
				let maxErrorSize = 4096;

				try {
					let fileStat = stat(CONFIG_FILE);
					if (fileStat) {
						if (fileStat.size > maxSize) {
							runtime = { exists: false, content: '', path: CONFIG_FILE, code: 'FILE_TOO_LARGE', message: 'runtime configuration exceeds 512 KiB' };
						} else {
							let raw = readfile(CONFIG_FILE) || '';
							runtime = {
								exists: raw != '',
								content: raw,
								path: CONFIG_FILE,
								code: raw != '' ? 'OK' : 'EMPTY',
								message: raw != '' ? '' : 'runtime configuration file is empty'
							};
						}
					}
				} catch (e) {
					runtime = { exists: false, content: '', path: CONFIG_FILE, code: 'READ_FAILED', message: 'unable to read runtime configuration' };
				}

				let hasServer = false;
				try {
					let current = cursor().get_all(UCI_CONFIG);
					if (current && type(current) == 'object') {
						for (let sectionName in current) {
							let section = current[sectionName];
							if (section && type(section) == 'object' && section['.type'] == 'server') {
								hasServer = true;
								break;
							}
						}
					}
				} catch (e) { }

				if (!hasServer) {
					request.reply({
						ok: true,
						service_running: service.running,
						code: 'NO_SERVER',
						candidate: {
							ok: false,
							exists: false,
							content: '',
							code: 'NO_SERVER',
							message: ''
						},
						runtime: runtime,
						equal: null
					});
					return;
				}

				return ubus.defer('file', 'exec', {
					command: '/etc/init.d/frpc-advanced',
					params: [ 'preview_config' ],
					env: {}
				}, function(code, response) {
					let candidate = {
						ok: false,
						exists: false,
						content: '',
						code: 'GENERATION_FAILED',
						message: 'unable to generate candidate configuration'
					};

					let stdout = '';
					let stderr = '';

					if (response && type(response) == 'object') {
						stdout = response.stdout || '';
						stderr = response.stderr || '';
					}

					if (length(stderr) > maxErrorSize)
						stderr = substr(stderr, length(stderr) - maxErrorSize);

					let exitCode = (response && type(response) == 'object') ? (response.code || 0) : (code || 1);

					if (exitCode == 0) {
						if (stdout != '' && length(stdout) <= maxSize) {
							candidate = {
								ok: true,
								exists: true,
								generated: true,
								content: stdout,
								code: 'OK',
								message: ''
							};
						} else if (stdout == '') {
							candidate.code = 'EMPTY';
							candidate.message = 'candidate configuration is empty';
						} else {
							candidate.code = 'FILE_TOO_LARGE';
							candidate.message = 'candidate configuration exceeds 512 KiB';
						}
					} else {
						if (stdout != '') {
							candidate.exists = true;
							candidate.content = stdout;
						}
						candidate.code = 'GENERATION_FAILED';
						candidate.message = stderr != '' ? stderr : 'candidate configuration generation failed';
					}

					let equal = null;
					let compareCode = 'UNKNOWN';

					if (!candidate.ok) {
						compareCode = candidate.code;
					} else if (!runtime.exists) {
						compareCode = 'RUNTIME_NOT_GENERATED';
					} else {
						let nc = normalize_config_for_compare(candidate.content);
						let nr = normalize_config_for_compare(runtime.content);
						if (nc == nr) {
							equal = true;
							compareCode = 'MATCH';
						} else {
							equal = false;
							compareCode = 'DIFFERENT';
						}
					}

					request.reply({
						ok: true,
						service_running: service.running,
						code: compareCode,
						candidate: candidate,
						runtime: runtime,
						equal: equal
					});
				});
			}
		},

		validate_backup: {
			args: { config: '' },
			call: function(request) {
				let stage = 'start';
				try {
					let raw = request && request.args ? request.args.config : null;
					let validation = parse_and_validate_backup(raw);
					if (!validation.ok)
						return validation;

					stage = 'read-current';
					let c = cursor();
					let current = c.get_all(UCI_CONFIG);
					let normalized = backup_from_uci(current);
					if (!normalized.ok)
						return normalized;

					stage = 'compare';
					let diff = compare_sections(pseudo_sections(normalized.backup), pseudo_sections(validation.backup));
					return {
						ok: true,
						code: 'OK',
						stage: 'complete',
						message: 'backup validation passed',
						section_count: validation.section_count,
						option_count: validation.option_count,
						diff: diff
					};
				}
				catch (e) {
					return { ok: false, code: 'INTERNAL_ERROR', stage: stage, message: '' + e };
				}
			}
		},

		restore_config: {
			args: { config: '' },
			call: function(request) {
				let stage = 'start';
				try {
					stage = 'read-service-state';
					let serviceState = read_service_state();

					stage = 'read-argument';
					let raw = request && request.args ? request.args.config : null;
					let validation = parse_and_validate_backup(raw);
					if (!validation.ok)
						return validation;

					stage = 'apply';
					let applied = apply_backup(UCI_CONFIG, validation.backup);
					if (!applied.ok)
						return applied;

					let success = {
						ok: true,
						code: 'OK',
						stage: 'complete',
						message: '',
						restored_sections: validation.section_count,
						restored_options: validation.option_count,
						config_restored: true,
						service_state: serviceState,
						runtime_synchronized: false
					};

					if (serviceState == 'stopped') {
						success.message = 'Configuration restored successfully, FRPC is currently not running.';
						return success;
					}
					if (serviceState == 'unknown') {
						success.message = 'Configuration restored successfully, FRPC running state is unknown.';
						return success;
					}

					stage = 'restart-service';
					return ubus.defer('file', 'exec', {
						command: '/etc/init.d/frpc-advanced',
						params: [ 'restart' ],
						env: {}
					}, function(code, response) {
						let responseOk = code == 0 && response && type(response) == 'object' && response.code == 0;
						let currentServiceState = read_service_state();
						if (responseOk && currentServiceState == 'running') {
							success.message = 'Configuration restored successfully, FRPC has been reloaded.';
							success.service_state = 'running';
							success.runtime_synchronized = true;
							request.reply(success);
							return;
						}

						let stderr = response && type(response) == 'object' ? (response.stderr || '') : '';
						if (length(stderr) > 4096)
							stderr = substr(stderr, length(stderr) - 4096);
						if (stderr == '') {
							if (currentServiceState == 'unknown')
								stderr = 'unable to read FRPC service state after restart';
							else if (currentServiceState == 'stopped')
								stderr = 'FRPC is not running after restart';
							else
								stderr = 'FRPC restart command failed';
						}

						request.reply({
							ok: false,
							code: 'SERVICE_RESTART_FAILED',
							stage: 'restart-service',
							message: stderr,
							config_restored: true,
							service_state: currentServiceState,
							runtime_synchronized: false
						});
					});
				}
				catch (e) {
					return { ok: false, code: 'INTERNAL_ERROR', stage: stage, message: '' + e };
				}
			}
		}
	}
};
